[ClassVersion("1.0.0"), FriendlyName("cChocoInstall")] 
class cChocoInstall : OMI_BaseResource
{
  [Key] string PackageName;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;  
};