[ClassVersion("1.0.0"), FriendlyName("cGitPull")] 
class cGitPull : OMI_BaseResource
{
  [Key] string RepositoryLocal;
  [Key] string RepositoryRemote;
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;  
};